access_token = '25476e0b-e277-4bc3-8103-ece504d8e7ab'
device_id = '025af955-895f-44d8-b6b8-20bd01c1647f'
license_key = 'Db30zw49-6b453XTt-z8Tu613W'
private_key = 'MDXA0s/Ek5I6fiOssEm4D6qVba1LVsWjsbdWcZgLb04='
