access_token = '38390e1b-0614-4ad6-ad76-4f68ced136e2'
device_id = '85264c0b-50e6-4f75-b06e-9826f2b0c792'
license_key = '4y9mR85T-98Z0juk7-Ah3f1I65'
private_key = 'kIm5zn4KfoKx7xibk0R0Te3aZPAQkTPOiGPP1+ixlWc='
